version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch:5
        volumes:
            # - /data/elasticsearch:/usr/share/elasticsearch/data
            - /data-etc/elasticsearch:/usr/share/elasticsearch/config
            - ./etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
            - ./etc/sg_config.yml:/usr/share/elasticsearch/config/searchguard/sg_config.yml
        ports:
            - "9200:9200"
            - "9300:9300"
        # user: "elasticsearch:elasticsearch"
        network_mode: bridge
        restart: always
    kibana:
        image: khezen/kibana
        ports:
            - "5601:5601"
        network_mode: bridge
        restart: always
        volumes:
            - /data-etc/kibana:/etc/kibana
            - ./etc/kibana/kibana.yml:/etc/kibana/kibana.yml
            - /data-etc/elasticsearch/searchguard/ssl/ca/root-ca.pem:/etc/elasticsearch/searchguard/ssl/ca/root-ca.pem
        links:
            - elasticsearch
